import type { Metadata } from "next";
import "./globals.css";

import { qualy } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={qualy.className}>
        {children}
      </body>
    </html>
  );
}
